version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/go:1.22
    steps:
      - run:
          name: Install upx
          command: sudo apt update && sudo apt install upx -y
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: 
          name: Build
          command: go build -C cmd/gowake/ -v -ldflags="-w -s"
      - run:
          name: Upx
          command: upx ./cmd/gowake/gowake
      - persist_to_workspace:
          root: ~/project
          paths: 
            - cmd/gowake/gowake       
  release:
    docker: 
        - image: cimg/base:current
    steps:
      - attach_workspace:
          at: ./
      - run: 
          name: Package
          command: tar cvfz ${CIRCLE_PROJECT_REPONAME}_${CIRCLE_TAG}_linux_amd64.tar.gz cmd/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}
      - run:
          name: Release    
          command: |
            curl -v \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/jedrw/${CIRCLE_PROJECT_REPONAME}/releases \
              -d '{"tag_name":"'$CIRCLE_TAG'","draft":false,"prerelease":false}'

            RELEASE_ID=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/jedrw/${CIRCLE_PROJECT_REPONAME}/releases/tags/${CIRCLE_TAG} \
              | jq '.id') 
          
            curl -v \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: $(file -b --mime-type ${CIRCLE_PROJECT_REPONAME}_${CIRCLE_TAG}_linux_amd64.tar.gz)" \
              https://uploads.github.com/repos/jedrw/${CIRCLE_PROJECT_REPONAME}/releases/$RELEASE_ID/assets?name=$(basename ${CIRCLE_PROJECT_REPONAME}_${CIRCLE_TAG}_linux_amd64.tar.gz) \
              --data-binary @${CIRCLE_PROJECT_REPONAME}_${CIRCLE_TAG}_linux_amd64.tar.gz

workflows:
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+/
      - release:
          context:
            - github
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+\.\d+\.\d+/

